// The build output set (SPEC 12.1, 13.1–13.3) — the pure derivation.
//
// Pure core (IMPLEMENTATION Architecture: output generation is deterministic
// and I/O-free; the workspace layer writes): over a validated workspace's
// analyses this module computes everything `xspec build` writes —
//
// - the generated TypeScript modules and companions of every spec source
//   (SPEC 13.1, via ./emission.ts);
// - the emitted Markdown, exactly while `markdown` is present with `emit`
//   true (SPEC 7.3): `NAME.mdx` emits `NAME.md`, placed per `markdown.outDir`
//   preserving workspace-relative paths, the default next to each source
//   (SPEC 3, 13.2);
// - the graph data (SPEC 13.3): the current snapshot with the derived-file
//   record set to exactly the paths generated by this build (13.4 — the
//   record orphan removal relies on);
// - the orphans (SPEC 12.1, 13.3, 13.4): recorded derived files the current
//   sources and configuration no longer generate, removed via their recorded
//   paths only — a missing or malformed record records nothing, and such
//   orphans stay outside xspec's knowledge.
//
// Only valid workspaces reach this derivation (SPEC 12.1: a failed build
// modifies nothing), so every value is a total, byte-deterministic function
// of (configuration, parsed sources, journal) — no wall clock, no
// randomness, no absolute paths (SPEC 12.0).

import { compareBytes, sortByBytes } from "./bytes.js";
import type { Configuration } from "./config.js";
import { canonicalOutDirPrefix } from "./discovery.js";
import type { GeneratedFile } from "./emission.js";
import { generateSpecModule } from "./emission.js";
import type { GraphData } from "./graph-data.js";
import {
  buildGraphSnapshot,
  GRAPH_DATA_PATH,
  recordedDerivedFiles,
} from "./graph-data.js";
import type { SpecFileAnalysis, WorkspaceGraph } from "./graph.js";
import type { NodeHashes } from "./hashes.js";
import type { WorkspaceTextModel } from "./text-model.js";

/** Everything one `xspec build` writes and removes (SPEC 12.1). */
export interface BuildOutputs {
  /**
   * Every derived file this build generates — generated TypeScript modules
   * and companions (SPEC 13.1), then emitted Markdown (13.2) — sources in
   * byte order of workspace-relative path, each source's files in a fixed
   * order (SPEC 12.0 determinism). Graph data is not among them: it is
   * carried separately as `graphData`.
   */
  readonly files: readonly GeneratedFile[];
  /**
   * SPEC 13.3: the graph data to store — the current snapshot, with the
   * derived-file record holding exactly the paths of `files`.
   */
  readonly graphData: GraphData;
  /**
   * SPEC 12.1, 13.3, 13.4: recorded derived files the current sources and
   * configuration no longer generate, in byte order — removed via these
   * recorded paths only.
   */
  readonly orphans: readonly string[];
  /**
   * The complete workspace-relative write set — every path of `files` plus
   * the graph-data path — for the SPEC 14.22 pre-write validation (writes
   * never traverse symbolic links; a command refuses the write and reports
   * it before modifying anything).
   */
  readonly writePaths: readonly string[];
}

/**
 * Derive the SPEC 12.1 build outputs of a validated workspace. `stored` is
 * the previously stored graph data (null when missing or malformed): its
 * recorded derived-file paths are the orphan-removal domain (SPEC 13.3,
 * 13.4). `hashes` must be the SPEC 5.5 computation over `graph`.
 */
export function computeBuildOutputs(
  configuration: Configuration,
  specs: readonly SpecFileAnalysis[],
  graph: WorkspaceGraph,
  textModel: WorkspaceTextModel,
  hashes: ReadonlyMap<string, NodeHashes>,
  stored: GraphData | null,
): BuildOutputs {
  // SPEC 12.0: deterministic output order — sources by byte order of
  // workspace-relative path (the classification already yields this order;
  // sorting keeps the derivation order-independent of its inputs).
  const ordered = sortByBytes(specs, (spec) => spec.document.path);

  const files: GeneratedFile[] = [];
  // SPEC 13.1: `NAME.mdx` generates `NAME.xspec.ts` and its companions in
  // the source file's directory.
  for (const spec of ordered) {
    files.push(...generateSpecModule(spec.document, textModel));
  }
  // SPEC 7.3/13.2: Markdown is emitted exactly while `markdown` is present
  // with `emit` true — `NAME.mdx` emits `NAME.md`, placed per
  // `markdown.outDir` preserving workspace-relative paths (SPEC 3).
  const markdown = configuration.markdown;
  if (markdown !== undefined && markdown.emit) {
    const prefix = canonicalOutDirPrefix(markdown.outDir) ?? "";
    for (const spec of ordered) {
      const specPath = spec.document.path;
      files.push({
        // SPEC 13.2: the `.mdx` source emits `.md` — the trailing "x"
        // dropped (discovered spec sources always end `.mdx`, SPEC 7.1).
        path: prefix + specPath.slice(0, -1),
        content: textModel.compiledMarkdown(spec.document),
      });
    }
  }

  const generated = new Set(files.map((file) => file.path));
  // SPEC 12.1/13.3/13.4: orphan removal via recorded paths only. The
  // graph-data path is never recorded (13.3 records the generated derived
  // files); a record naming it anyway is dropped defensively — the store is
  // rewritten, never removed, by a build.
  const orphans = [...new Set(recordedDerivedFiles(stored))]
    .filter((path) => !generated.has(path) && path !== GRAPH_DATA_PATH)
    .sort(compareBytes);

  return {
    files,
    graphData: {
      snapshot: buildGraphSnapshot(graph, hashes),
      // SPEC 13.3: the paths of the derived files most recently generated —
      // updated only by generation.
      derivedFiles: [...generated].sort(compareBytes),
    },
    orphans,
    writePaths: [...files.map((file) => file.path), GRAPH_DATA_PATH],
  };
}
